package fr.lta.testing;

/**
 * {@link ExpectedDataLocationPath} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractExpectedDataLocationPathAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ExpectedDataLocationPathAssert extends AbstractExpectedDataLocationPathAssert<ExpectedDataLocationPathAssert, ExpectedDataLocationPath> {

  /**
   * Creates a new <code>{@link ExpectedDataLocationPathAssert}</code> to make assertions on actual ExpectedDataLocationPath.
   * @param actual the ExpectedDataLocationPath we want to make assertions on.
   */
  public ExpectedDataLocationPathAssert(ExpectedDataLocationPath actual) {
    super(actual, ExpectedDataLocationPathAssert.class);
  }

  /**
   * An entry point for ExpectedDataLocationPathAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myExpectedDataLocationPath)</code> and get specific assertion with code completion.
   * @param actual the ExpectedDataLocationPath we want to make assertions on.
   * @return a new <code>{@link ExpectedDataLocationPathAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ExpectedDataLocationPathAssert assertThat(ExpectedDataLocationPath actual) {
    return new ExpectedDataLocationPathAssert(actual);
  }
}
